# Generated by Django 6.0.3 on 2026-03-13 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracklisting',
            options={'managed': True, 'verbose_name': 'Track Listing', 'verbose_name_plural': 'Track Listings'},
        ),
    ]
