# Generated by Django 6.0.3 on 2026-03-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260313_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracklisting',
            name='show_id',
        ),
        migrations.AddField(
            model_name='tracklisting',
            name='canonical_track',
            field=models.ForeignKey(blank=True, db_column='track_fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracklist', to='core.track'),
        ),
        migrations.AddField(
            model_name='tracklisting',
            name='show',
            field=models.ForeignKey(db_column='Show_ID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracks', to='core.showdetail'),
            preserve_default=False,
        ),
    ]
